local combatMD1 = Combat()
combatMD1:setArea(createCombatArea(AREA_MEDUSA_MD1_ICEBLUECIRCLE))
local combatMD2 = Combat()
combatMD2:setArea(createCombatArea(AREA_MEDUSA_MD2_ICEBLUECIRCLE))
local combatMD3 = Combat()
combatMD3:setArea(createCombatArea(AREA_MEDUSA_MD3_ICEBLUECIRCLE))
local combatMD4 = Combat()
combatMD4:setArea(createCombatArea(AREA_MEDUSA_MD4_ICEBLUECIRCLE))
local combatMD5 = Combat()
combatMD5:setArea(createCombatArea(AREA_MEDUSA_MD5_ICEBLUECIRCLE))
local combatMD6 = Combat()
combatMD6:setArea(createCombatArea(AREA_MEDUSA_MD6_ICEFIELD))
local combatMD7 = Combat()
combatMD7:setArea(createCombatArea(AREA_MEDUSA_MD7_YELLOWENERGY))
local combatMD8 = Combat()
combatMD8:setArea(createCombatArea(AREA_MEDUSA_MD8_YELLOWENERGY))
local combatMD9 = Combat()
combatMD9:setArea(createCombatArea(AREA_MEDUSA_MD9_BLUEENERGY))
local combatMD10 = Combat()
combatMD10:setArea(createCombatArea(AREA_MEDUSA_MD10_PURPLEENERGY))
local combatMD11 = Combat()
combatMD11:setArea(createCombatArea(AREA_MEDUSA_MD11_ICEBLUECIRCLE))
local combatMD12 = Combat()
combatMD12:setArea(createCombatArea(AREA_MEDUSA_MD12_FIREFIELD))
local combatMD13 = Combat()
combatMD13:setArea(createCombatArea(AREA_MEDUSA_MD13_FIREFIELD))
local combatMD14 = Combat()
combatMD14:setArea(createCombatArea(AREA_MEDUSA_MD14_PURPLEENERGY))
local combatMD15 = Combat()
combatMD15:setArea(createCombatArea(AREA_MEDUSA_MD15_FIREFIELD))
local combatMD16 = Combat()
combatMD16:setArea(createCombatArea(AREA_MEDUSA_MD16_FIREFIELD))
local combatMD17 = Combat()
combatMD17:setArea(createCombatArea(AREA_MEDUSA_MD17_FIREFIELD))
local combatMD18 = Combat()
combatMD18:setArea(createCombatArea(AREA_MEDUSA_MD18_FIREFIELD))
-- function onGetFormulaValues1(player, level, maglevel)
-- 	local min = (level / 5) + (maglevel * 1.2) + 7
-- 	local max = (level / 5) + (maglevel * 2.8) + 17
-- 	return -min, -max
-- end


-- combatMD1:setCallback(CALLBACK_PARAM_LEVELMAGICVALUE, "onGetFormulaValues")

setCombatFormula(combatMD1, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD2, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD3, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD4, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD5, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD6, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD7, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD8, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD9, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD10, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD11, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD12, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD13, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD14, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD15, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD16, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD17, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatMD18, COMBAT_FORMULA_LEVELMAGIC, -1)

function sendAttackIceBlueCircle(creatureId, var, combatName)
    combatName:setParameter(COMBAT_PARAM_TYPE, COMBAT_ICEDAMAGE)
    combatName:setParameter(COMBAT_PARAM_EFFECT, 38)
    combatName:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_ENERGY)
    combatName:execute(Creature(creatureId), var)
end

function sendAttackFireField(creatureId, var, combatName)
    combatName:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
    combatName:setParameter(COMBAT_PARAM_EFFECT, 16)
    combatName:execute(Creature(creatureId), var)
end

function sendAttackIceField(creatureId, var, combatName)
    combatName:setParameter(COMBAT_PARAM_TYPE, COMBAT_ICEDAMAGE)
    combatName:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_ICEATTACK)
    combatName:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_SMALLICE)
    combatName:execute(Creature(creatureId), var)
end

function sendAttackYellowEnergy(creatureId, var, combatName)
    combatName:setParameter(COMBAT_PARAM_TYPE, COMBAT_ENERGYDAMAGE)
    combatName:setParameter(COMBAT_PARAM_EFFECT, 49)
    combatName:execute(Creature(creatureId), var)
end

function sendAttackBlueEnergy(creatureId, var, combatName)
    combatName:setParameter(COMBAT_PARAM_TYPE, COMBAT_ENERGYDAMAGE)
    combatName:setParameter(COMBAT_PARAM_EFFECT, 12)
    combatName:execute(Creature(creatureId), var)
end

function sendAttackPurpleEnergy(creatureId, var, combatName)
    combatName:setParameter(COMBAT_PARAM_TYPE, COMBAT_ENERGYDAMAGE)
    combatName:setParameter(COMBAT_PARAM_EFFECT, 48)
    combatName:execute(Creature(creatureId), var)
end

local rune = Spell("rune")

function rune.onCastSpell(creature, var, isHotkey)
    addEvent(sendAttackIceBlueCircle, 0, creature:getId(), var, combatMD1)
    addEvent(sendAttackIceBlueCircle, 200, creature:getId(), var, combatMD2)
    addEvent(sendAttackIceBlueCircle, 400, creature:getId(), var, combatMD3)
    addEvent(sendAttackIceBlueCircle, 600, creature:getId(), var, combatMD4)
    addEvent(sendAttackIceBlueCircle, 800, creature:getId(), var, combatMD5)
    addEvent(sendAttackIceField, 1000, creature:getId(), var, combatMD6)
    addEvent(sendAttackYellowEnergy, 1200, creature:getId(), var, combatMD7)
    addEvent(sendAttackYellowEnergy, 1400, creature:getId(), var, combatMD8)
    addEvent(sendAttackBlueEnergy, 1600, creature:getId(), var, combatMD9)
    addEvent(sendAttackPurpleEnergy, 1800, creature:getId(), var, combatMD10)
    addEvent(sendAttackIceBlueCircle, 2000, creature:getId(), var, combatMD11)
    addEvent(sendAttackFireField, 2200, creature:getId(), var, combatMD12)
    addEvent(sendAttackFireField, 2400, creature:getId(), var, combatMD13)
    addEvent(sendAttackPurpleEnergy, 2600, creature:getId(), var, combatMD14)
    addEvent(sendAttackFireField, 2800, creature:getId(), var, combatMD15)
    addEvent(sendAttackFireField, 3000, creature:getId(), var, combatMD16)
    addEvent(sendAttackFireField, 3200, creature:getId(), var, combatMD17)
    addEvent(sendAttackFireField, 3400, creature:getId(), var, combatMD18)
    return true
end

-- rune:id(115)
rune:group("attack")
rune:name("medusa rune")
rune:castSound(SOUND_EFFECT_TYPE_SPELL_OR_RUNE)
rune:impactSound(SOUND_EFFECT_TYPE_SPELL_GREAT_FIREBALL_RUNE)
rune:runeId(3151)
rune:allowFarUse(true)
rune:charges(0)
rune:level(2500)
rune:magicLevel(4)
rune:groupCooldown(3 * 1000)
rune:isBlocking(false)
rune:register()
