local combatS1 = Combat()
combatS1:setArea(createCombatArea(AREA_MORGANA_S1_DEATH))
local combatS2 = Combat()
combatS2:setArea(createCombatArea(AREA_MORGANA_S2_DEATH))
local combatS3 = Combat()
combatS3:setArea(createCombatArea(AREA_MORGANA_S3_DEATH))
local combatS4 = Combat()
combatS4:setArea(createCombatArea(AREA_MORGANA_S4_DEATH))
local combatS5 = Combat()
combatS5:setArea(createCombatArea(AREA_MORGANA_S5_DEATH))
local combatS6 = Combat()
combatS6:setArea(createCombatArea(AREA_MORGANA_S6_FIRE))
local combatS7 = Combat()
combatS7:setArea(createCombatArea(AREA_MORGANA_S7_FIRE))
local combatS8 = Combat()
combatS8:setArea(createCombatArea(AREA_MORGANA_S8_FIRE))
local combatS9 = Combat()
combatS9:setArea(createCombatArea(AREA_MORGANA_S9_FIRE))
local combatS10 = Combat()
combatS10:setArea(createCombatArea(AREA_MORGANA_S10_FIRE))
local combatS11 = Combat()
combatS11:setArea(createCombatArea(AREA_MORGANA_S11_FIRE))
local combatS12 = Combat()
combatS12:setArea(createCombatArea(AREA_MORGANA_S12_FIRE))
local combatS13 = Combat()
combatS13:setArea(createCombatArea(AREA_MORGANA_S13_FIRE))
local combatS14 = Combat()
combatS14:setArea(createCombatArea(AREA_MORGANA_S14_FIRE))
local combatS15 = Combat()
combatS15:setArea(createCombatArea(AREA_MORGANA_S15_FIRE))
local combatS16 = Combat()
combatS16:setArea(createCombatArea(AREA_MORGANA_S16_FIRE))

-- function onGetFormulaValues1(player, level, maglevel)
-- 	local min = (level / 5) + (maglevel * 1.2) + 7
-- 	local max = (level / 5) + (maglevel * 2.8) + 17
-- 	return -min, -max
-- end


-- combatS1:setCallback(CALLBACK_PARAM_LEVELMAGICVALUE, "onGetFormulaValues")

setCombatFormula(combatS1, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS2, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS3, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS4, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS5, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS6, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS7, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS8, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS9, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS10, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS11, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS12, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS13, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS14, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS15, COMBAT_FORMULA_LEVELMAGIC, -1)
setCombatFormula(combatS16, COMBAT_FORMULA_LEVELMAGIC, -1)

function sendAttackMort(creatureId, var, combatName)
    combatName:setParameter(COMBAT_PARAM_TYPE, COMBAT_DEATHDAMAGE)
    combatName:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_MORTAREA)
    combatName:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_SUDDENDEATH)
    combatName:execute(Creature(creatureId), var)
end

function sendAttackFire(creatureId, var, combatName)
    combatName:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
    combatName:setParameter(COMBAT_PARAM_EFFECT, 6)
    combatName:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_FIRE)
    combatName:execute(Creature(creatureId), var)
end

function sendAttackExplosion(creatureId, var, combatName)
    combatName:setParameter(COMBAT_PARAM_TYPE, COMBAT_FIREDAMAGE)
    combatName:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_FIREAREA)
    combatName:execute(Creature(creatureId), var)
end

local rune = Spell("rune")

function rune.onCastSpell(creature, var, isHotkey)
    addEvent(sendAttackMort, 0, creature:getId(), var, combatS1)
    addEvent(sendAttackMort, 200, creature:getId(), var, combatS2)
    addEvent(sendAttackMort, 400, creature:getId(), var, combatS3)
    addEvent(sendAttackMort, 600, creature:getId(), var, combatS4)
    addEvent(sendAttackMort, 800, creature:getId(), var, combatS5)
    addEvent(sendAttackFire, 1000, creature:getId(), var, combatS6)
    addEvent(sendAttackFire, 1200, creature:getId(), var, combatS7)
    addEvent(sendAttackFire, 1400, creature:getId(), var, combatS8)
    addEvent(sendAttackFire, 1600, creature:getId(), var, combatS9)
    addEvent(sendAttackFire, 1800, creature:getId(), var, combatS10)
    addEvent(sendAttackFire, 2000, creature:getId(), var, combatS11)
    addEvent(sendAttackFire, 2200, creature:getId(), var, combatS12)
    addEvent(sendAttackFire, 2400, creature:getId(), var, combatS13)
    addEvent(sendAttackFire, 2600, creature:getId(), var, combatS6)
    addEvent(sendAttackFire, 2800, creature:getId(), var, combatS7)
    addEvent(sendAttackFire, 3000, creature:getId(), var, combatS8)
    addEvent(sendAttackFire, 3200, creature:getId(), var, combatS9)
    addEvent(sendAttackExplosion, 3600, creature:getId(), var, combatS14)
    addEvent(sendAttackExplosion, 4000, creature:getId(), var, combatS15)
    addEvent(sendAttackExplosion, 4400, creature:getId(), var, combatS16)
    addEvent(sendAttackExplosion, 4800, creature:getId(), var, combatS14)
    addEvent(sendAttackExplosion, 5200, creature:getId(), var, combatS15)
    addEvent(sendAttackExplosion, 5600, creature:getId(), var, combatS16)
    return true
end

-- rune:id(115)
rune:group("attack")
rune:name("morgana rune")
rune:castSound(SOUND_EFFECT_TYPE_SPELL_OR_RUNE)
rune:impactSound(SOUND_EFFECT_TYPE_SPELL_GREAT_FIREBALL_RUNE)
rune:runeId(3194)
rune:allowFarUse(true)
rune:charges(0)
rune:level(30)
rune:magicLevel(4)
rune:cooldown(2 * 1000)
rune:groupCooldown(2 * 1000)
rune:isBlocking(true)
rune:register()
